kind = "api"
previewPath = "/api"
title = "BrightSideReporter API"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api"]

[services.development]
run = "PORT=8080 node /home/runner/workspace/artifacts/api-server/index.js"

[services.production]

[services.production.build]
args = ["echo", "no build needed"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["node", "/home/runner/workspace/artifacts/api-server/index.js"]

[services.production.run.env]
PORT = "8080"
NODE_ENV = "production"

[services.production.health.startup]
path = "/api/subreddits"
